version: 2
jobs:
  build:
    working_directory: ~/verified-vyper-contracts/tests

    docker:
      - image: python:3.6.7

    steps:
      - checkout:
          path: ~/verified-vyper-contracts
      - run: apt-get update
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Lint
          command: flake8
