version: 2
jobs:
  build:
    docker:
      - image: python:3.6.7

    steps:
      - checkout
      - run: apt-get update
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
